name: Run Specific Gatling Simulation

on:
  workflow_dispatch:
    inputs:
      simulationClass:
        description: 'Please Select a Gatling Simulation Class'
        required: true
        type: choice
        default: 'social_network.ComposePostSimulation'
        options:
          - 'social_network.ComposePostSimulation'
          - 'social_network.FollowUsersSimulation'
          - 'bookstore.UserRegistrationSimulation'
          - 'bookstore.BuyBooksSimulation'
      users:
        description: 'Number of users to be Ramped up'
        required: true
        default: '1'
      duration:
        description: 'Ramp up duration'
        required: true
        default: '5'
      csvFileName:
        description: 'Name of the CSV file to be used'
        required: true
        default: 'test_users.csv'

jobs:
  gatling-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run Gatling Simulation and Extract Report Directory
        id: run_sim
        run: |
          OUTPUT=$(./gradlew gatlingRun --simulation=${{ github.event.inputs.simulationClass }} -Dusers=${{ github.event.inputs.users }} -Dduration=${{ github.event.inputs.duration }} -DcsvFileName=${{ github.event.inputs.csvFileName }})
          echo "$OUTPUT"
          REPORT_DIR=$(echo "$OUTPUT" | grep -oP '(?<=Reports generated, please open the following file: file://).*index.html' | sed 's#/index.html##')
          REPORT_NAME=$(basename "$REPORT_DIR")
          echo "Report directory: $REPORT_DIR"
          echo "Report name: $REPORT_NAME"
          echo "::set-output name=report_dir::$REPORT_DIR"
          echo "::set-output name=report_name::$REPORT_NAME"

      - name: Zip Gatling Report Directory
        run: |
          REPORT_DIR="${{ steps.run_sim.outputs.report_dir }}"
          ZIP_NAME="${{ steps.run_sim.outputs.report_name }}.zip"
          zip -r "$ZIP_NAME" "$REPORT_DIR"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

      - name: Upload Gatling Report Zip as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gatling-report
          path: ${{ env.ZIP_NAME }}